/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.names;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner keyboard = new Scanner(System.in);
        String nombre;
        
        System.out.println("Ingresa tu nombre:");
        nombre = keyboard.nextLine();
        
        System.out.println("Bienvenido "+nombre);
    }
}
